services:
  smtp-relay:
    image: boky/postfix:v5.1.0
    container_name: smtp-relay
    restart: unless-stopped
    env_file:
      - .env
    environment:
      ALLOWED_SENDER_DOMAINS: gmail.com
      RELAYHOST: ${SMTP_RELAYHOST}
      RELAYHOST_USERNAME: ${SMTP_USERNAME}
      RELAYHOST_PASSWORD: ${SMTP_PASSWORD}
      SMTP_SERVER_HOSTNAME: smtp-relay
      POSTFIX_smtp_tls_wrappermode: "yes"
      POSTFIX_smtp_tls_security_level: "encrypt"
    ports:
      - "127.0.0.1:2525:25"
    networks:
      - proxy

networks:
  proxy:
    external: true
